//This file is automatically generated by generator.lua from https://github.com/cimgui/imnodes
//based on imnodes.h file version XXX from https://github.com/Nelarius/imnodes
#include "imgui.h"
#include "imgui_internal.h"
#include "./imgui-node-editor/imgui_node_editor.h"
#include "cimnodes_editor.h"
#include <cstring>

// Check that the layout of the C POD structs match their C++
// counterparts. Necessary for array arguments to work.
static_assert(sizeof(NodeId_c) == sizeof(ax::NodeEditor::NodeId), "NodeId_c size mismatch");
static_assert(alignof(NodeId_c) == alignof(ax::NodeEditor::NodeId), "NodeId_c alignment mismatch");
static_assert(sizeof(PinId_c) == sizeof(ax::NodeEditor::PinId), "PinId_c size mismatch");
static_assert(alignof(PinId_c) == alignof(ax::NodeEditor::PinId), "PinId_c alignment mismatch");
static_assert(sizeof(LinkId_c) == sizeof(ax::NodeEditor::LinkId), "LinkId_c size mismatch");
static_assert(alignof(LinkId_c) == alignof(ax::NodeEditor::LinkId), "LinkId_c alignment mismatch");

static inline ax::NodeEditor::NodeId ConvertToCPP_NodeId(const NodeId_c& src)
{
    return ax::NodeEditor::NodeId(src.value);
}
static inline NodeId_c ConvertFromCPP_NodeId(const ax::NodeEditor::NodeId& src)
{
    NodeId_c dest;
    dest.value = src.Get();
    return dest;
}
static inline ax::NodeEditor::PinId ConvertToCPP_PinId(const PinId_c& src)
{
    return ax::NodeEditor::PinId(src.value);
}
static inline PinId_c ConvertFromCPP_PinId(const ax::NodeEditor::PinId& src)
{
    PinId_c dest;
    dest.value = src.Get();
    return dest;
}
static inline ax::NodeEditor::LinkId ConvertToCPP_LinkId(const LinkId_c& src)
{
    return ax::NodeEditor::LinkId(src.value);
}
static inline LinkId_c ConvertFromCPP_LinkId(const ax::NodeEditor::LinkId& src)
{
    LinkId_c dest;
    dest.value = src.Get();
    return dest;
}

static inline ImVec2 ConvertToCPP_ImVec2(const ImVec2_c& src)
{
    ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}
static inline ImVec2_c ConvertFromCPP_ImVec2(const ImVec2& src)
{
    ImVec2_c dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}
static inline ImVec4 ConvertToCPP_ImVec4(const ImVec4_c& src)
{
    ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}
static inline ImVec4_c ConvertFromCPP_ImVec4(const ImVec4& src)
{
    ImVec4_c dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}CIMGUI_API Config* ax_NodeEditor_Config_Config_Config(void)
{
    return IM_NEW(Config)();
}
CIMGUI_API void Config_destroy(Config* self)
{
    IM_DELETE(self);
}
CIMGUI_API void ax_NodeEditor_SetCurrentEditor(EditorContext* ctx)
{
    return ax::NodeEditor::SetCurrentEditor(ctx);
}
CIMGUI_API EditorContext* ax_NodeEditor_GetCurrentEditor()
{
    return ax::NodeEditor::GetCurrentEditor();
}
CIMGUI_API EditorContext* ax_NodeEditor_CreateEditor(const Config* config)
{
    return ax::NodeEditor::CreateEditor(config);
}
CIMGUI_API void ax_NodeEditor_DestroyEditor(EditorContext* ctx)
{
    return ax::NodeEditor::DestroyEditor(ctx);
}
CIMGUI_API const Config* ax_NodeEditor_GetConfig(EditorContext* ctx)
{
    return &ax::NodeEditor::GetConfig(ctx);
}
CIMGUI_API cimnodes_editor_Style* ax_NodeEditor_GetStyle()
{
    return &ax::NodeEditor::GetStyle();
}
CIMGUI_API const char* ax_NodeEditor_GetStyleColorName(StyleColor colorIndex)
{
    return ax::NodeEditor::GetStyleColorName(colorIndex);
}
CIMGUI_API void ax_NodeEditor_PushStyleColor(StyleColor colorIndex,const ImVec4_c color)
{
    return ax::NodeEditor::PushStyleColor(colorIndex,ConvertToCPP_ImVec4(color));
}
CIMGUI_API void ax_NodeEditor_PopStyleColor(int count)
{
    return ax::NodeEditor::PopStyleColor(count);
}
CIMGUI_API void ax_NodeEditor_PushStyleVar_Float(StyleVar varIndex,float value)
{
    return ax::NodeEditor::PushStyleVar(varIndex,value);
}
CIMGUI_API void ax_NodeEditor_PushStyleVar_Vec2(StyleVar varIndex,const ImVec2_c value)
{
    return ax::NodeEditor::PushStyleVar(varIndex,ConvertToCPP_ImVec2(value));
}
CIMGUI_API void ax_NodeEditor_PushStyleVar_Vec4(StyleVar varIndex,const ImVec4_c value)
{
    return ax::NodeEditor::PushStyleVar(varIndex,ConvertToCPP_ImVec4(value));
}
CIMGUI_API void ax_NodeEditor_PopStyleVar(int count)
{
    return ax::NodeEditor::PopStyleVar(count);
}
CIMGUI_API void ax_NodeEditor_Begin(const char* id,const ImVec2_c size)
{
    return ax::NodeEditor::Begin(id,ConvertToCPP_ImVec2(size));
}
CIMGUI_API void ax_NodeEditor_End()
{
    return ax::NodeEditor::End();
}
CIMGUI_API void ax_NodeEditor_BeginNode(NodeId_c id)
{
    return ax::NodeEditor::BeginNode(ConvertToCPP_NodeId(id));
}
CIMGUI_API void ax_NodeEditor_BeginPin(PinId_c id,PinKind kind)
{
    return ax::NodeEditor::BeginPin(ConvertToCPP_PinId(id),kind);
}
CIMGUI_API void ax_NodeEditor_PinRect(const ImVec2_c a,const ImVec2_c b)
{
    return ax::NodeEditor::PinRect(ConvertToCPP_ImVec2(a),ConvertToCPP_ImVec2(b));
}
CIMGUI_API void ax_NodeEditor_PinPivotRect(const ImVec2_c a,const ImVec2_c b)
{
    return ax::NodeEditor::PinPivotRect(ConvertToCPP_ImVec2(a),ConvertToCPP_ImVec2(b));
}
CIMGUI_API void ax_NodeEditor_PinPivotSize(const ImVec2_c size)
{
    return ax::NodeEditor::PinPivotSize(ConvertToCPP_ImVec2(size));
}
CIMGUI_API void ax_NodeEditor_PinPivotScale(const ImVec2_c scale)
{
    return ax::NodeEditor::PinPivotScale(ConvertToCPP_ImVec2(scale));
}
CIMGUI_API void ax_NodeEditor_PinPivotAlignment(const ImVec2_c alignment)
{
    return ax::NodeEditor::PinPivotAlignment(ConvertToCPP_ImVec2(alignment));
}
CIMGUI_API void ax_NodeEditor_EndPin()
{
    return ax::NodeEditor::EndPin();
}
CIMGUI_API void ax_NodeEditor_Group(const ImVec2_c size)
{
    return ax::NodeEditor::Group(ConvertToCPP_ImVec2(size));
}
CIMGUI_API void ax_NodeEditor_EndNode()
{
    return ax::NodeEditor::EndNode();
}
CIMGUI_API bool ax_NodeEditor_BeginGroupHint(NodeId_c nodeId)
{
    return ax::NodeEditor::BeginGroupHint(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API ImVec2_c ax_NodeEditor_GetGroupMin()
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::GetGroupMin());
}
CIMGUI_API ImVec2_c ax_NodeEditor_GetGroupMax()
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::GetGroupMax());
}
CIMGUI_API ImDrawList* ax_NodeEditor_GetHintForegroundDrawList()
{
    return ax::NodeEditor::GetHintForegroundDrawList();
}
CIMGUI_API ImDrawList* ax_NodeEditor_GetHintBackgroundDrawList()
{
    return ax::NodeEditor::GetHintBackgroundDrawList();
}
CIMGUI_API void ax_NodeEditor_EndGroupHint()
{
    return ax::NodeEditor::EndGroupHint();
}
CIMGUI_API ImDrawList* ax_NodeEditor_GetNodeBackgroundDrawList(NodeId_c nodeId)
{
    return ax::NodeEditor::GetNodeBackgroundDrawList(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API bool ax_NodeEditor_Link(LinkId_c id,PinId_c startPinId,PinId_c endPinId,const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::Link(ConvertToCPP_LinkId(id),ConvertToCPP_PinId(startPinId),ConvertToCPP_PinId(endPinId),ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API void ax_NodeEditor_Flow(LinkId_c linkId,FlowDirection direction)
{
    return ax::NodeEditor::Flow(ConvertToCPP_LinkId(linkId),direction);
}
CIMGUI_API bool ax_NodeEditor_BeginCreate(const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::BeginCreate(ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API bool ax_NodeEditor_QueryNewLink_Nil(PinId_c* startId,PinId_c* endId)
{
    return ax::NodeEditor::QueryNewLink(reinterpret_cast<ax::NodeEditor::PinId*>(startId),reinterpret_cast<ax::NodeEditor::PinId*>(endId));
}
CIMGUI_API bool ax_NodeEditor_QueryNewLink_Vec4(PinId_c* startId,PinId_c* endId,const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::QueryNewLink(reinterpret_cast<ax::NodeEditor::PinId*>(startId),reinterpret_cast<ax::NodeEditor::PinId*>(endId),ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API bool ax_NodeEditor_QueryNewNode_Nil(PinId_c* pinId)
{
    return ax::NodeEditor::QueryNewNode(reinterpret_cast<ax::NodeEditor::PinId*>(pinId));
}
CIMGUI_API bool ax_NodeEditor_QueryNewNode_Vec4(PinId_c* pinId,const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::QueryNewNode(reinterpret_cast<ax::NodeEditor::PinId*>(pinId),ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API bool ax_NodeEditor_AcceptNewItem_Nil()
{
    return ax::NodeEditor::AcceptNewItem();
}
CIMGUI_API bool ax_NodeEditor_AcceptNewItem_Vec4(const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::AcceptNewItem(ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API void ax_NodeEditor_RejectNewItem_Nil()
{
    return ax::NodeEditor::RejectNewItem();
}
CIMGUI_API void ax_NodeEditor_RejectNewItem_Vec4(const ImVec4_c color,float thickness)
{
    return ax::NodeEditor::RejectNewItem(ConvertToCPP_ImVec4(color),thickness);
}
CIMGUI_API void ax_NodeEditor_EndCreate()
{
    return ax::NodeEditor::EndCreate();
}
CIMGUI_API bool ax_NodeEditor_BeginDelete()
{
    return ax::NodeEditor::BeginDelete();
}
CIMGUI_API bool ax_NodeEditor_QueryDeletedLink(LinkId_c* linkId,PinId_c* startId,PinId_c* endId)
{
    return ax::NodeEditor::QueryDeletedLink(reinterpret_cast<ax::NodeEditor::LinkId*>(linkId),reinterpret_cast<ax::NodeEditor::PinId*>(startId),reinterpret_cast<ax::NodeEditor::PinId*>(endId));
}
CIMGUI_API bool ax_NodeEditor_QueryDeletedNode(NodeId_c* nodeId)
{
    return ax::NodeEditor::QueryDeletedNode(reinterpret_cast<ax::NodeEditor::NodeId*>(nodeId));
}
CIMGUI_API bool ax_NodeEditor_AcceptDeletedItem(bool deleteDependencies)
{
    return ax::NodeEditor::AcceptDeletedItem(deleteDependencies);
}
CIMGUI_API void ax_NodeEditor_RejectDeletedItem()
{
    return ax::NodeEditor::RejectDeletedItem();
}
CIMGUI_API void ax_NodeEditor_EndDelete()
{
    return ax::NodeEditor::EndDelete();
}
CIMGUI_API void ax_NodeEditor_SetNodePosition(NodeId_c nodeId,const ImVec2_c editorPosition)
{
    return ax::NodeEditor::SetNodePosition(ConvertToCPP_NodeId(nodeId),ConvertToCPP_ImVec2(editorPosition));
}
CIMGUI_API void ax_NodeEditor_SetGroupSize(NodeId_c nodeId,const ImVec2_c size)
{
    return ax::NodeEditor::SetGroupSize(ConvertToCPP_NodeId(nodeId),ConvertToCPP_ImVec2(size));
}
CIMGUI_API ImVec2_c ax_NodeEditor_GetNodePosition(NodeId_c nodeId)
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::GetNodePosition(ConvertToCPP_NodeId(nodeId)));
}
CIMGUI_API ImVec2_c ax_NodeEditor_GetNodeSize(NodeId_c nodeId)
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::GetNodeSize(ConvertToCPP_NodeId(nodeId)));
}
CIMGUI_API void ax_NodeEditor_CenterNodeOnScreen(NodeId_c nodeId)
{
    return ax::NodeEditor::CenterNodeOnScreen(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API void ax_NodeEditor_SetNodeZPosition(NodeId_c nodeId,float z)
{
    return ax::NodeEditor::SetNodeZPosition(ConvertToCPP_NodeId(nodeId),z);
}
CIMGUI_API float ax_NodeEditor_GetNodeZPosition(NodeId_c nodeId)
{
    return ax::NodeEditor::GetNodeZPosition(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API void ax_NodeEditor_RestoreNodeState(NodeId_c nodeId)
{
    return ax::NodeEditor::RestoreNodeState(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API void ax_NodeEditor_Suspend()
{
    return ax::NodeEditor::Suspend();
}
CIMGUI_API void ax_NodeEditor_Resume()
{
    return ax::NodeEditor::Resume();
}
CIMGUI_API bool ax_NodeEditor_IsSuspended()
{
    return ax::NodeEditor::IsSuspended();
}
CIMGUI_API bool ax_NodeEditor_IsActive()
{
    return ax::NodeEditor::IsActive();
}
CIMGUI_API bool ax_NodeEditor_HasSelectionChanged()
{
    return ax::NodeEditor::HasSelectionChanged();
}
CIMGUI_API int ax_NodeEditor_GetSelectedObjectCount()
{
    return ax::NodeEditor::GetSelectedObjectCount();
}
CIMGUI_API int ax_NodeEditor_GetSelectedNodes(NodeId_c* nodes,int size)
{
    return ax::NodeEditor::GetSelectedNodes(reinterpret_cast<ax::NodeEditor::NodeId*>(nodes),size);
}
CIMGUI_API int ax_NodeEditor_GetSelectedLinks(LinkId_c* links,int size)
{
    return ax::NodeEditor::GetSelectedLinks(reinterpret_cast<ax::NodeEditor::LinkId*>(links),size);
}
CIMGUI_API bool ax_NodeEditor_IsNodeSelected(NodeId_c nodeId)
{
    return ax::NodeEditor::IsNodeSelected(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API bool ax_NodeEditor_IsLinkSelected(LinkId_c linkId)
{
    return ax::NodeEditor::IsLinkSelected(ConvertToCPP_LinkId(linkId));
}
CIMGUI_API void ax_NodeEditor_ClearSelection()
{
    return ax::NodeEditor::ClearSelection();
}
CIMGUI_API void ax_NodeEditor_SelectNode(NodeId_c nodeId,bool append)
{
    return ax::NodeEditor::SelectNode(ConvertToCPP_NodeId(nodeId),append);
}
CIMGUI_API void ax_NodeEditor_SelectLink(LinkId_c linkId,bool append)
{
    return ax::NodeEditor::SelectLink(ConvertToCPP_LinkId(linkId),append);
}
CIMGUI_API void ax_NodeEditor_DeselectNode(NodeId_c nodeId)
{
    return ax::NodeEditor::DeselectNode(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API void ax_NodeEditor_DeselectLink(LinkId_c linkId)
{
    return ax::NodeEditor::DeselectLink(ConvertToCPP_LinkId(linkId));
}
CIMGUI_API bool ax_NodeEditor_DeleteNode(NodeId_c nodeId)
{
    return ax::NodeEditor::DeleteNode(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API bool ax_NodeEditor_DeleteLink(LinkId_c linkId)
{
    return ax::NodeEditor::DeleteLink(ConvertToCPP_LinkId(linkId));
}
CIMGUI_API bool ax_NodeEditor_HasAnyLinks_NodeId(NodeId_c nodeId)
{
    return ax::NodeEditor::HasAnyLinks(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API bool ax_NodeEditor_HasAnyLinks_PinId(PinId_c pinId)
{
    return ax::NodeEditor::HasAnyLinks(ConvertToCPP_PinId(pinId));
}
CIMGUI_API int ax_NodeEditor_BreakLinks_NodeId(NodeId_c nodeId)
{
    return ax::NodeEditor::BreakLinks(ConvertToCPP_NodeId(nodeId));
}
CIMGUI_API int ax_NodeEditor_BreakLinks_PinId(PinId_c pinId)
{
    return ax::NodeEditor::BreakLinks(ConvertToCPP_PinId(pinId));
}
CIMGUI_API void ax_NodeEditor_NavigateToContent(float duration)
{
    return ax::NodeEditor::NavigateToContent(duration);
}
CIMGUI_API void ax_NodeEditor_NavigateToSelection(bool zoomIn,float duration)
{
    return ax::NodeEditor::NavigateToSelection(zoomIn,duration);
}
CIMGUI_API bool ax_NodeEditor_ShowNodeContextMenu(NodeId_c* nodeId)
{
    return ax::NodeEditor::ShowNodeContextMenu(reinterpret_cast<ax::NodeEditor::NodeId*>(nodeId));
}
CIMGUI_API bool ax_NodeEditor_ShowPinContextMenu(PinId_c* pinId)
{
    return ax::NodeEditor::ShowPinContextMenu(reinterpret_cast<ax::NodeEditor::PinId*>(pinId));
}
CIMGUI_API bool ax_NodeEditor_ShowLinkContextMenu(LinkId_c* linkId)
{
    return ax::NodeEditor::ShowLinkContextMenu(reinterpret_cast<ax::NodeEditor::LinkId*>(linkId));
}
CIMGUI_API bool ax_NodeEditor_ShowBackgroundContextMenu()
{
    return ax::NodeEditor::ShowBackgroundContextMenu();
}
CIMGUI_API void ax_NodeEditor_EnableShortcuts(bool enable)
{
    return ax::NodeEditor::EnableShortcuts(enable);
}
CIMGUI_API bool ax_NodeEditor_AreShortcutsEnabled()
{
    return ax::NodeEditor::AreShortcutsEnabled();
}
CIMGUI_API bool ax_NodeEditor_BeginShortcut()
{
    return ax::NodeEditor::BeginShortcut();
}
CIMGUI_API bool ax_NodeEditor_AcceptCut()
{
    return ax::NodeEditor::AcceptCut();
}
CIMGUI_API bool ax_NodeEditor_AcceptCopy()
{
    return ax::NodeEditor::AcceptCopy();
}
CIMGUI_API bool ax_NodeEditor_AcceptPaste()
{
    return ax::NodeEditor::AcceptPaste();
}
CIMGUI_API bool ax_NodeEditor_AcceptDuplicate()
{
    return ax::NodeEditor::AcceptDuplicate();
}
CIMGUI_API bool ax_NodeEditor_AcceptCreateNode()
{
    return ax::NodeEditor::AcceptCreateNode();
}
CIMGUI_API int ax_NodeEditor_GetActionContextSize()
{
    return ax::NodeEditor::GetActionContextSize();
}
CIMGUI_API int ax_NodeEditor_GetActionContextNodes(NodeId_c* nodes,int size)
{
    return ax::NodeEditor::GetActionContextNodes(reinterpret_cast<ax::NodeEditor::NodeId*>(nodes),size);
}
CIMGUI_API int ax_NodeEditor_GetActionContextLinks(LinkId_c* links,int size)
{
    return ax::NodeEditor::GetActionContextLinks(reinterpret_cast<ax::NodeEditor::LinkId*>(links),size);
}
CIMGUI_API void ax_NodeEditor_EndShortcut()
{
    return ax::NodeEditor::EndShortcut();
}
CIMGUI_API float ax_NodeEditor_GetCurrentZoom()
{
    return ax::NodeEditor::GetCurrentZoom();
}
CIMGUI_API NodeId_c ax_NodeEditor_GetHoveredNode()
{
    return ConvertFromCPP_NodeId(ax::NodeEditor::GetHoveredNode());
}
CIMGUI_API PinId_c ax_NodeEditor_GetHoveredPin()
{
    return ConvertFromCPP_PinId(ax::NodeEditor::GetHoveredPin());
}
CIMGUI_API LinkId_c ax_NodeEditor_GetHoveredLink()
{
    return ConvertFromCPP_LinkId(ax::NodeEditor::GetHoveredLink());
}
CIMGUI_API NodeId_c ax_NodeEditor_GetDoubleClickedNode()
{
    return ConvertFromCPP_NodeId(ax::NodeEditor::GetDoubleClickedNode());
}
CIMGUI_API PinId_c ax_NodeEditor_GetDoubleClickedPin()
{
    return ConvertFromCPP_PinId(ax::NodeEditor::GetDoubleClickedPin());
}
CIMGUI_API LinkId_c ax_NodeEditor_GetDoubleClickedLink()
{
    return ConvertFromCPP_LinkId(ax::NodeEditor::GetDoubleClickedLink());
}
CIMGUI_API bool ax_NodeEditor_IsBackgroundClicked()
{
    return ax::NodeEditor::IsBackgroundClicked();
}
CIMGUI_API bool ax_NodeEditor_IsBackgroundDoubleClicked()
{
    return ax::NodeEditor::IsBackgroundDoubleClicked();
}
CIMGUI_API ImGuiMouseButton ax_NodeEditor_GetBackgroundClickButtonIndex()
{
    return ax::NodeEditor::GetBackgroundClickButtonIndex();
}
CIMGUI_API ImGuiMouseButton ax_NodeEditor_GetBackgroundDoubleClickButtonIndex()
{
    return ax::NodeEditor::GetBackgroundDoubleClickButtonIndex();
}
CIMGUI_API bool ax_NodeEditor_GetLinkPins(LinkId_c linkId,PinId_c* startPinId,PinId_c* endPinId)
{
    return ax::NodeEditor::GetLinkPins(ConvertToCPP_LinkId(linkId),reinterpret_cast<ax::NodeEditor::PinId*>(startPinId),reinterpret_cast<ax::NodeEditor::PinId*>(endPinId));
}
CIMGUI_API bool ax_NodeEditor_PinHadAnyLinks(PinId_c pinId)
{
    return ax::NodeEditor::PinHadAnyLinks(ConvertToCPP_PinId(pinId));
}
CIMGUI_API ImVec2_c ax_NodeEditor_GetScreenSize()
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::GetScreenSize());
}
CIMGUI_API ImVec2_c ax_NodeEditor_ScreenToCanvas(const ImVec2_c pos)
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::ScreenToCanvas(ConvertToCPP_ImVec2(pos)));
}
CIMGUI_API ImVec2_c ax_NodeEditor_CanvasToScreen(const ImVec2_c pos)
{
    return ConvertFromCPP_ImVec2(ax::NodeEditor::CanvasToScreen(ConvertToCPP_ImVec2(pos)));
}
CIMGUI_API int ax_NodeEditor_GetNodeCount()
{
    return ax::NodeEditor::GetNodeCount();
}
CIMGUI_API int ax_NodeEditor_GetOrderedNodeIds(NodeId_c* nodes,int size)
{
    return ax::NodeEditor::GetOrderedNodeIds(reinterpret_cast<ax::NodeEditor::NodeId*>(nodes),size);
}


///manuals
CIMGUI_API NodeId_c ax_NodeEditor_NodeId(uintptr_t val)
{
	NodeId_c self;
	self.value = val;
	return self;
}
CIMGUI_API PinId_c ax_NodeEditor_PinId(uintptr_t val)
{
	PinId_c self;
	self.value = val;
	return self;
}
CIMGUI_API LinkId_c ax_NodeEditor_LinkId(uintptr_t val)
{
	LinkId_c self;
	self.value = val;
	return self;
}
CIMGUI_API uintptr_t ax_NodeEditor_NodeId_value(NodeId_c self)
{
	return self.value;
}
CIMGUI_API uintptr_t ax_NodeEditor_PinId_value(PinId_c self)
{
	return self.value;
}
CIMGUI_API uintptr_t ax_NodeEditor_LinkId_value(LinkId_c self)
{
	return self.value;
}



